from .datagen import (
    generate_sequence,
    rename_registers,
    permute_regs,
    reorder_independent,
    insert_nops,
    remove_nops,
    strength_reduce,
    decompose_immediate,
    mutate_immediate,
    mutate_opcode,
    generate_equivalence_pair,
    generate_near_equivalence_pair,
    generate_training_sample,
)
